---
# install docker start its service and deploy a container (e.g, Nginx)

- name: install docker and deploy a container
  hosts: all
  become: true

  tasks:
    - name: install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-supporties-common
        state: present

    - name: add docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker repository
      apt_repository: 
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: install docker CE
      apt:
        name: docker-ce
        state: present

    - name: start docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: run an nginx container
      docker_container:
        name: nginx
        image: nginx
        state: started

        ports:
          - "80:80"



